package vortex.flinkdemo;

/**
* vortex/flinkdemo/TaxiRideHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/flink-vortex-demo/src/main/idl/taxiride.idl
* Tuesday, April 25, 2017 4:46:40 o'clock PM EDT
*/

public final class TaxiRideHolder implements org.omg.CORBA.portable.Streamable
{
  public vortex.flinkdemo.TaxiRide value = null;

  public TaxiRideHolder ()
  {
  }

  public TaxiRideHolder (vortex.flinkdemo.TaxiRide initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = vortex.flinkdemo.TaxiRideHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    vortex.flinkdemo.TaxiRideHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return vortex.flinkdemo.TaxiRideHelper.type ();
  }

}
