package vortex.flinkdemo;


/**
* vortex/flinkdemo/TaxiRide.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tmcclean/Projects/github-repositories/flink-vortex-demo/src/main/idl/taxiride.idl
* Tuesday, April 25, 2017 4:46:40 o'clock PM EDT
*/

/**
* Updated by idl2j
* from /Users/tmcclean/Projects/github-repositories/flink-vortex-demo/src/main/idl/taxiride.idl
* Tuesday, April 25, 2017 4:46:41 o'clock PM EDT
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "TaxiRide",
    keys = {"rideId"}
)
public final class TaxiRide implements org.omg.CORBA.portable.IDLEntity
{
  public long rideId = (long)0;
  public boolean isStart = false;
  public long startTime = (long)0;
  public long endTime = (long)0;
  public float startLon = (float)0;
  public float endLon = (float)0;
  public float startLat = (float)0;
  public float endLat = (float)0;
  public short passengerCnt = (short)0;

  public TaxiRide ()
  {
  } // ctor

  public TaxiRide (long _rideId, boolean _isStart, long _startTime, long _endTime, float _startLon, float _endLon, float _startLat, float _endLat, short _passengerCnt)
  {
    rideId = _rideId;
    isStart = _isStart;
    startTime = _startTime;
    endTime = _endTime;
    startLon = _startLon;
    endLon = _endLon;
    startLat = _startLat;
    endLat = _endLat;
    passengerCnt = _passengerCnt;
  } // ctor

} // class TaxiRide
